"""
Cleanup tool for GraphINVENT2.

Removes stale output runs, preprocessed HDF5/split-SMILES files, and
_previous_run_* backup directories.  Always shows an itemised preview and
requires the user to type "yes" before anything is deleted.

Usage examples
--------------
# Preview everything that would be removed (dry run)
python cleanup.py --all --dry-run

# Clean output directories only
python cleanup.py --outputs

# Clean preprocessed data only (HDF5 + auto-generated split .smi files)
python cleanup.py --preprocessed

# Clean _previous_run_* backup directories only
python cleanup.py --backups

# Everything at once
python cleanup.py --all

# Scope to specific paths
python cleanup.py --outputs --output-dir ./output/debug
python cleanup.py --preprocessed --dataset-dir data/datasets/debug data/datasets/test
"""

import argparse
import os
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SPLIT_SMI = {"train.smi", "valid.smi", "test.smi"}
_SPLIT_CSV = {"train.csv", "valid.csv", "test.csv"}
_HDF_SUFFIXES = {".h5"}
_BACKUP_PREFIX = "_previous_run_"


def _fmt_size(path: Path) -> str:
    """Return human-readable disk usage for a file or directory."""
    try:
        if path.is_dir():
            total = sum(f.stat().st_size for f in path.rglob("*") if f.is_file())
        else:
            total = path.stat().st_size
        for unit in ("B", "KB", "MB", "GB"):
            if total < 1024:
                return f"{total:.0f} {unit}"
            total /= 1024
        return f"{total:.1f} TB"
    except OSError:
        return "?"


def _collect_outputs(output_dir: Path) -> list[Path]:
    """
    Collect all job-run directories under *output_dir*.

    Structure:  output/<dataset>/<job_type>/<job_name>/
                output/<dataset>/<job_type>/<job_name>/tensorboard/

    Everything at depth >= 1 inside output_dir is considered a target so the
    user can remove a whole dataset subtree or a single job run depending on
    which output_dir they pass.
    """
    targets: list[Path] = []
    if not output_dir.exists():
        return targets
    for child in sorted(output_dir.iterdir()):
        if child.is_dir():
            targets.append(child)
    return targets


def _collect_preprocessed(dataset_dirs: list[Path]) -> list[Path]:
    """
    Collect preprocessed artefacts in each dataset directory.

    Per-directory rules
    -------------------
    * .h5 files (train.h5, valid.h5, test.h5) are always collected.
    * preprocessing_params.json is collected alongside the .h5 files.
    * train.smi / valid.smi / test.smi are collected **only** when at least
      one non-split .smi file also exists in the same directory (indicating
      they were auto-generated by the split step rather than supplied by the
      user).
    * train.csv / valid.csv / test.csv are collected under the same condition.
    """
    targets: list[Path] = []
    for ddir in dataset_dirs:
        if not ddir.is_dir():
            continue

        all_files = list(ddir.iterdir())
        smi_files = {f.name for f in all_files if f.suffix == ".smi"}
        has_original_smi = bool(smi_files - _SPLIT_SMI)

        for f in sorted(all_files):
            if not f.is_file():
                continue
            if f.suffix in _HDF_SUFFIXES:
                targets.append(f)
            elif f.name == "preprocessing_params.json":
                # Only remove if there are also .h5 files to remove
                if any(ff.suffix in _HDF_SUFFIXES for ff in all_files if ff.is_file()):
                    targets.append(f)
            elif f.name in _SPLIT_SMI and has_original_smi:
                targets.append(f)
            elif f.name in _SPLIT_CSV and has_original_smi:
                targets.append(f)

    return targets


def _collect_backups(search_dirs: list[Path]) -> list[Path]:
    """
    Recursively collect all _previous_run_* directories inside *search_dirs*.
    """
    targets: list[Path] = []
    for root in search_dirs:
        if not root.exists():
            continue
        for dirpath, dirnames, _ in os.walk(root):
            for d in sorted(dirnames):
                if d.startswith(_BACKUP_PREFIX):
                    targets.append(Path(dirpath) / d)
            # Prune backup dirs so we don't recurse into them and double-list
            dirnames[:] = [d for d in dirnames if not d.startswith(_BACKUP_PREFIX)]
    return targets


def _auto_discover_dataset_dirs(base: Path) -> list[Path]:
    """Return immediate subdirectories of *base* that look like dataset dirs."""
    if not base.is_dir():
        return []
    return sorted(d for d in base.iterdir() if d.is_dir())


# ---------------------------------------------------------------------------
# Confirmation prompt
# ---------------------------------------------------------------------------


def _confirm(targets: list[Path], dry_run: bool) -> bool:
    """Print the itemised list and ask for "yes" / "no"."""
    if not targets:
        print("Nothing to remove.")
        return False

    print()
    print("The following items will be permanently deleted:")
    print()
    for t in targets:
        label = "DIR " if t.is_dir() else "FILE"
        print(f"  [{label}]  {t}  ({_fmt_size(t)})")
    print()

    if dry_run:
        print("Dry-run mode — nothing deleted.")
        return False

    answer = (
        input('Type "yes" to confirm deletion, or "no" to cancel: ').strip().lower()
    )
    if answer == "yes":
        return True
    print("Cancelled.")
    return False


# ---------------------------------------------------------------------------
# Deletion
# ---------------------------------------------------------------------------


def _delete(targets: list[Path]) -> None:
    errors: list[str] = []
    for t in targets:
        try:
            if t.is_dir():
                shutil.rmtree(t)
                print(f"  Removed dir:  {t}")
            elif t.is_file():
                t.unlink()
                print(f"  Removed file: {t}")
        except OSError as exc:
            errors.append(f"  ERROR removing {t}: {exc}")

    if errors:
        print("\nSome items could not be removed:")
        for e in errors:
            print(e)
        sys.exit(1)

    print(f"\nDone — {len(targets)} item(s) removed.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Clean up stale GraphINVENT2 outputs and preprocessed data.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # What to clean
    what = parser.add_argument_group("what to clean (at least one required)")
    what.add_argument(
        "--outputs",
        action="store_true",
        help="Remove directories inside --output-dir (job run outputs).",
    )
    what.add_argument(
        "--preprocessed",
        action="store_true",
        help=(
            "Remove .h5 files and auto-generated split .smi/.csv files from "
            "dataset directories.  Split .smi files are only removed when an "
            "original (non-split) .smi file also exists in the same directory."
        ),
    )
    what.add_argument(
        "--backups",
        action="store_true",
        help="Remove _previous_run_* backup directories from outputs and datasets.",
    )
    what.add_argument(
        "--all",
        action="store_true",
        help="Equivalent to --outputs --preprocessed --backups.",
    )

    # Where to look
    where = parser.add_argument_group("where to look")
    where.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output"),
        metavar="PATH",
        help="Root output directory to clean (default: ./output).",
    )
    where.add_argument(
        "--dataset-dir",
        type=Path,
        nargs="+",
        default=None,
        metavar="PATH",
        help=(
            "One or more dataset directories to check for preprocessed files "
            "and backups.  If omitted, all subdirectories of data/datasets/ "
            "are used automatically."
        ),
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be removed without actually deleting anything.",
    )

    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    # Expand --all
    if args.all:
        args.outputs = True
        args.preprocessed = True
        args.backups = True

    if not (args.outputs or args.preprocessed or args.backups):
        print(
            "error: specify at least one of --outputs, --preprocessed, --backups, or --all.\n"
            "Run  python cleanup.py --help  for usage."
        )
        sys.exit(1)

    # Resolve dataset directories
    if args.dataset_dir is not None:
        dataset_dirs = args.dataset_dir
    else:
        dataset_dirs = _auto_discover_dataset_dirs(Path("data/datasets"))

    # Build the combined target list (deduplicated, stable order)
    seen: set[Path] = set()
    targets: list[Path] = []

    def _add(paths: list[Path]) -> None:
        for p in paths:
            rp = p.resolve()
            if rp not in seen:
                seen.add(rp)
                targets.append(p)

    if args.outputs and not args.backups:
        # Collect output subdirs but skip backup dirs (they'll be handled separately
        # if --backups is also set; if not, leave them in place).
        _add(
            [
                p
                for p in _collect_outputs(args.output_dir)
                if not p.name.startswith(_BACKUP_PREFIX)
            ]
        )
    elif args.outputs:
        _add(_collect_outputs(args.output_dir))

    if args.preprocessed:
        _add(_collect_preprocessed(dataset_dirs))

    if args.backups:
        search_roots = list(dataset_dirs) + (
            [args.output_dir] if args.output_dir.exists() else []
        )
        _add(_collect_backups(search_roots))

    if _confirm(targets, dry_run=args.dry_run):
        _delete(targets)


if __name__ == "__main__":
    main()
